### ISSUE TITLE
No response when clicking "open" or the hash after send transaction.

### ISSUE THREAD

**Issue by oregonisaac** [raedahgroup/dcrios#103]
A confirmation of transaction showing the txid comes up displayed as a hyperlink, but neither the link nor "open" functions.  Clicking should send the id to https://explorer.dcrdata.org/search?search=[txid]

![open txid screen](https://user-images.githubusercontent.com/4402603/46987103-7ec8ba00-d0a7-11e8-8876-35974a26f87b.jpg)

**Comment by Guang168** [comment]
i had the same issue.
