### ISSUE TITLE
Incorrect input outputs and not clickable link under history tab

### ISSUE THREAD

**Issue by Guang168** [raedahgroup/dcrios#106]
Under history tab when click on a particular outgoing transaction. 
1. inputs and outputs were same for all transaction. 
2. input shows my default wallet 274.0 (i never had that amount in my wallet) 
3. links in outputs are not clickable 
4. Transaction hash should be a clickable link which directs to the explorer ? 

![wechatimg5](https://user-images.githubusercontent.com/43533453/46992687-e03b6800-d13d-11e8-82ea-7541715179ac.jpeg)
![wechatimg4](https://user-images.githubusercontent.com/43533453/46992688-e03b6800-d13d-11e8-8685-d7fae9739966.jpeg)

**Comment by macsleven** [comment]
This was fixed here #218 & #204
