### ISSUE TITLE
New transaction shows twice

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#223]
The first two transactions in this page are the same. Clicking the first one works fine while the second crashes the app
![simulator screen shot - iphone xr - 2019-03-02 at 02 52 51](https://user-images.githubusercontent.com/19960200/53675420-52988900-3c96-11e9-8000-1250a757ad7d.png)

**Comment by macsleven** [comment]
this only happens when using a simulator..it does not render as physical device
