### ISSUE TITLE
Use constants for preference keys 

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#260]
Code contains hardcoded preference keys used in different parts of the code and can be replaced with a constant then referenced globally.

**Comment by itswisdomagain** [comment]
Just seeing this issue. I've started doing this cleanup gradually for a while now. I added a new swift file for this purpose in #400: https://github.com/raedahgroup/dcrios/blob/master/Decred%20Wallet/Utils/Settings.swift

Subsequent work on this issue can build on that.
