### ISSUE TITLE
"Transaction Details" Page display is overlapping

### ISSUE THREAD

**Issue by 0x5826** [raedahgroup/dcrios#290]
"Transaction Details" Outputs display is overlapping

**Comment by macsleven** [comment]
Please can you reply with a screenshot and the phone used.thank you

**Comment by 0x5826** [comment]
iPhone 8 plus v12.1.4
![image](https://user-images.githubusercontent.com/6051672/55043902-314b7280-5073-11e9-8359-9698f598157d.png)
