### ISSUE TITLE
Navigation bar scaling wrongly on an iPad

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#320]
The sync info at the bottom of the navigation bar appears too big on an iPad Pro (6th generation)
![Simulator Screen Shot - iPad (6th generation) - 2019-04-07 at 16 36 31](https://user-images.githubusercontent.com/19960200/55686062-da884780-5954-11e9-8f45-667a09ec19ef.png)

**Comment by itswisdomagain** [comment]
The entire nav menu is too wide also
