### ISSUE TITLE
ui: consistent password request interface

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/dcrios#343]
I've noticed that most times, the app uses a full page to request the user's startup or spending password. Other times, such as when deleting the wallet from settings, an alert dialog is used. We should aim for a consistent password retrieval pattern.

I personally think an alert dialog fits most use cases as it does not needlessly migrate the user away from the current task (doing so is generally bad UX). The exception to this would be the Startup Password prompt, which is required before the app can be loaded.

**Comment by macsleven** [comment]
fixed in #568
