### ISSUE TITLE
Send page functionality review

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#352]
- X to remove send to address should always be present when there is info to clear, not just when in editing mode. Actually now that I test it, x button to clear the address line doesnt even work. It just exits editing mode. This needs to be fixed. Correct behavior is to clear the address input line.
- Taping to change the position of the cursor on the line while editing is not working. Only moves to the front or end of the number, cant select in the middle.
- Is there no button to close the keyboard on iOS devices? Only way I see is to find some other area of the screen to tap on which is pretty unintuitive.
- Send page, SEND button should be greyed out and inctive when form information is not filled out and valid. Currently the Send button actually works even when the input fields are invalid. 
- "Destination address is not valid"  needs a period on the end.
- Send page, confirmation dialog is suppose to come up after tapping send instead of going straight to pin input. Confirmation is currently showing after pin input.
- Send page, 'from' account selector is staying open even when tapping away from it.

- send page, password input on send dialog, return button on the onscreen keyboard is not performing any function. Should close or activate send when pressed.

**Comment by macsleven** [comment]
IOS Textfield behaves differently from android, to move the cursor you have to place your finger on it and move the cursor not just tapping.
The clear buttons clears the address line.
SEND  button works accordingly.
maybe you are running an old version.

**Comment by raedah** [comment]
Clear button is not working, at least on ipod touch. note, it does seem to work if I press just to the left of the x where there is an empty space. It seems the image and the touch are are not aligned.

Regarding iOS textfields, understood.

Send button is activating when there are errors showing, such as invalid address.

**Comment by itswisdomagain** [comment]
> * Send page, 'from' account selector is staying open even when tapping away from it.

This affects all pages where there is a dropdown (e.g. receive). Will be corrected in a different PR. #411 is a preferred solution.
