### ISSUE TITLE
Syncronization page

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#356]
-Crash, app has quit on me several times during initial synchronization. I have to restart it each time, but its picking up from where it left off.
-Discovering used addresses progress stays at 0%, so thats not working like android does.  dcrios status just looks frozen while discovering is happening.

**Comment by itswisdomagain** [comment]
I'm migrating sync progress calculation codes to dcrlibwallet and then updating dcrios to use dcrlibwallet master. This should resolve both issues identified.
