### ISSUE TITLE
Nav menu cleanup

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#359]
-Nav side menu should show some kind of down and up arrows on the top and bottom to indicate when it is scrollable for small screens. Also, the amount of space between menu items is much too large.
-Total Balance line is unreadable on ipod. icon is too big, label is larger then amount.

**Comment by macsleven** [comment]
> Nav side menu should show some kind of down and up arrows on the top and bottom to indicate when it is scrollable for small screens.

This is moved to #294
