### ISSUE TITLE
App keep showing scanning after wallet sync

### ISSUE THREAD

**Issue by macsleven** [raedahgroup/dcrios#378]
when the app is minimised for some minutes and resume, it starts scanning and get stucked on the screen.

<img width="300" src="https://user-images.githubusercontent.com/794430/57800476-6e65e400-7749-11e9-8588-e4d4ac3179fe.jpg">
<img width="300" src="https://user-images.githubusercontent.com/794430/57800481-702fa780-7749-11e9-8b64-d737836704c5.jpg">

**Comment by itswisdomagain** [comment]
Fixed in https://github.com/raedahgroup/dcrlibwallet/pull/26/files
