### ISSUE TITLE
improve tab usability on pin/pass page

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#384]
Many users have given feedback that the tab selected is not clear. A black outline on the tabs is probably the solution.

**Comment by C-ollins** [comment]
<img src="https://user-images.githubusercontent.com/19960200/57974884-98244280-79b7-11e9-9306-b6fc32fa42d5.jpeg" height="500">
<img src="https://user-images.githubusercontent.com/19960200/57974885-98bcd900-79b7-11e9-99cd-db005c10b24c.jpeg" height="500">
