### ISSUE TITLE
App crash after wallet delete

### ISSUE THREAD

**Issue by macsleven** [raedahgroup/dcrios#385]
The app crashes after wallet is successfully deleted as the app re-displays the splash screen.
Error is related to the timer that updates the best block age display on the navigation menu.

See https://github.com/raedahgroup/dcrios/blob/master/Decred%20Wallet/Features/Navigation%20Menu/NavigationMenuViewController.swift#L282-L288

![Screenshot 2019-05-16 at 3 07 38 AM](https://user-images.githubusercontent.com/794430/57821256-c6bbd680-7787-11e9-8b24-2312fb3e3ec2.png)

**Comment by itswisdomagain** [comment]
I just got this crash, appears it wasn't fixed.

**Comment by itswisdomagain** [comment]
Now fixed in #444
