### ISSUE TITLE
sync estimate time remaining get wacky after app sleep

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#393]
If the app sleeps during sync, when I resume it the estimated time is much high 5x higher. It seems to be taking account of the time it slept and adding that into the estimation.

Also got some even crazier % complete status returns where it shows 100% or 97% complete before jumping backwards.

**Comment by C-ollins** [comment]
I restarted the app while it was rescanning 
![IMG_8904](https://user-images.githubusercontent.com/19960200/57965819-56f14b80-7941-11e9-98a2-5764da7ec3eb.PNG)
