### ISSUE TITLE
crash on pin failure

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#403]
"When I create a new account or send a transaction and get the password wrong when using a PIN password, it goes to a blank password and then crashes."

**Comment by itswisdomagain** [comment]
I don't get a crash when I try to create new account. I get the following instead:

**With PIN set**
<img width="300" alt="Screenshot 2019-05-21 at 9 42 39 PM" src="https://user-images.githubusercontent.com/18400051/58129429-9f468d00-7c11-11e9-8b7c-2b60aa1f04ee.png">
**With password set**
<img width="300" alt="Screenshot 2019-05-21 at 9 44 09 PM" src="https://user-images.githubusercontent.com/18400051/58129431-9fdf2380-7c11-11e9-8824-84a02dc75225.png">
