### ISSUE TITLE
crash when sending unconfirmed funds

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#405]
"In settings if I turn on send unconfirmed funds, my amount will show up. But if I try to send the dcr after I input the password the app crashes. Could be related to the previous pin issue."

**Comment by macsleven** [comment]
This issue can not be duplicated on master.

**Comment by C-ollins** [comment]
I just sent some unconfirmed funds https://testnet.dcrdata.org/tx/1e9da6f9dc537037aa89df82d0d350767e7ffb52f6f9cb819ce44d44bcbe10c5 App did not crash
