### ISSUE TITLE
App freezes right before creating wallet

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#417]
I haven't tried this with password but the app stays like this for about 5 seconds before creating wallet. The log doesn't show any activity and the "Creating Wallet" log appears after the 5 seconds.
<img src="https://user-images.githubusercontent.com/19960200/58418872-fff61f80-8080-11e9-8e6d-cc54541ac175.PNG" width="300">

**Comment by raedah** [comment]
What is causing this?

**Comment by itswisdomagain** [comment]
> What is causing this? This is the same issue I had noticed.

Yes it is. Need to reconfirm that this issue still exists though.

**Comment by itswisdomagain** [comment]
This issue no longer exist in master.
