### ISSUE TITLE
iPod touch form factor does not fit

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#43]
I was able to run the iOS wallet on my iPod touch. I was not able to get past the wallet creation stage with the seed. The iPod touch has a small screen, and I am unable to view the seed it creates for me. The words run off the screen to the right.

**Comment by macsleven** [comment]
https://github.com/raedahgroup/dcrios/pull/69

**Comment by macsleven** [comment]
This was resolved in 
https://github.com/raedahgroup/dcrios/pull/69
