### ISSUE TITLE
Seed Restore: Add ability to insert missed words (add/remove extra row)

### ISSUE THREAD

**Issue by chillviben** [raedahgroup/dcrios#441]
**Problem:**  When restoring wallet from seed, if user accidentally skips, say, `word #6`, and doesn't realize it until after they entered the last word, there is no way to go back and insert the missed word. You have to delete most of the list and start over.

**Add ability to Insert Row:**  Allow user to move cursor to end of `word #5`, then press `return key` to push the list down and create a blank `word #6` row.

> **Conditions:** 
>* Maintain max of 33 row limit; If all rows below already contain words, do not insert new row.
>* If the next row down is already blank, do not insert new row, but move cursor down.

**Add ability to Delete Row:** If cursor is active on a blank row, and the `delete key` is pressed, delete row and move cursor up to end of previous row.

**Comment by raedah** [comment]
One thing we could do is mark red any words that don't match the correct order. I'm told that the seed words alternate between even and odd from the word list.

**Comment by macsleven** [comment]
fixed in #527
