### ISSUE TITLE
ui: PIN confirmation issue

### ISSUE THREAD

**Issue by SovereignNode** [raedahgroup/dcrios#449]
When I chose the PIN option after verifying the seed phrase I had a very minor issue.

I chose 6 digits PIN first. All good. In the confirmation of PIN phase, when I enter the last digit of the PIN, it snaps to '6'. I verified and it does work like this, but it seemed like a bug to me and perhaps a bit confusing.

Best,

**Comment by raedah** [comment]
I agree. We should be able to display more then 5 dots before switching to showing the number. We can refer to dcrandroid behavior which shows many more dots.
