### ISSUE TITLE
Rescan blockchain UI improvements

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/dcrios#451]
Add cancel rescan icon and show progress bar as in Android:
<img src="https://user-images.githubusercontent.com/18400051/59061042-64438b00-889a-11e9-9715-f5946535a63d.jpg" width="300">

**Comment by raedah** [comment]
Does the wallet recover safely if interrupted in the middle of a rescan?

**Comment by itswisdomagain** [comment]
Made obsolete by new UI design.
