### ISSUE TITLE
Clean up folder names

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#47]
Cleaning up the folder names in the dcrios repo.  Lower case and without spaces.

refers to 
*Decred Wallet.xcodeproj
*Decred Wallet.xcworkspace
*Decred Wallet
*Decred WalletTests

**Comment by ensoreus** [comment]
https://github.com/raedahgroup/dcrios/pull/49

**Comment by macsleven** [comment]
This was resolved in https://github.com/raedahgroup/dcrios/pull/51
