### ISSUE TITLE
Verify seed UI: 2.0

### ISSUE THREAD

**Issue by macsleven** [raedahgroup/dcrios#507]
https://gallery.io/projects/MCHbtQVoQ2HCZXGcfotOfnw9/files/MCESIDIcOrnLL2KtLfFUaHNn

**Comment by bgptr** [comment]
Hi, I am working on this and I have a question.
On the `write down` view which is the scrollable area?

![screenshot](https://user-images.githubusercontent.com/52497040/67016237-28e28400-f0f8-11e9-8423-2142ad9e2afd.png)
