### ISSUE TITLE
Seed Restore: Unable to select words from suggestion list

### ISSUE THREAD

**Issue by chillviben** [raedahgroup/dcrios#604]
DCR Wallet (mainnet & testnet)
iPad Mini 13.2.2
v1.0.1 / build 2020-02-26

When restoring wallet from seed, I enter a word, then suggestions come up.
Selecting the first word on the suggestion list works, but tapping on any other word on that list fails. 
![2020-03-03_17-18-53](https://user-images.githubusercontent.com/51382093/75835310-5f513080-5d73-11ea-9884-42f8f9c132bc.png)
In the picture above,  I can tap on _'seabird'_ and that works, but if I choose _'select'_, _'sentence_', or _'sensation'_, the suggestions disappear and I'm left with this:
![2020-03-03_17-22-46](https://user-images.githubusercontent.com/51382093/75835564-0a61ea00-5d74-11ea-921b-344e52dc887f.png)

**Comment by macsleven** [comment]
fixed in #527
