### ISSUE TITLE
x to close button touch area not large enough

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#640]
1 wallet needs backup msg. X is not easy to tap.

**Comment by neddoz** [comment]
@raedah Could you color more of how big did you want the icon?

**Comment by raedah** [comment]
Main idea is "so it works". Currently user attempts to tap it do nothing most times.

**Comment by neddoz** [comment]
Alright!

**Comment by macsleven** [comment]
fixed in https://github.com/raedahgroup/dcrios/pull/654
