### ISSUE TITLE
More button should always return to top level page

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrios#651]
When a user taps the More button, it is going back to whatever sub page they were previously viewing. It should always go to the top level page.

Also, more->settings page has an x to get back, but the rest of the pages have a back arrow to get back. It should be consistent.

**Comment by neddoz** [comment]
@raedah  Please move this to in-progress on the board as there is a PR for it.

**Comment by macsleven** [comment]
fixed in https://github.com/raedahgroup/dcrios/pull/657
