### ISSUE TITLE
Receive Screen - Cut off on iPhone SE

### ISSUE THREAD

**Issue by oregonisaac** [raedahgroup/dcrios#71]
![receive screen in dcrwallet ios](https://user-images.githubusercontent.com/4402603/45913546-5cfe4f00-bde9-11e8-8413-7e0c2dfb9327.jpg)

The text is cut off in my iPhone SE.  Probably designed for a larger iPhone screen.

**Comment by macsleven** [comment]
This was resolved in
https://github.com/raedahgroup/dcrios/pull/91
