### ISSUE TITLE
Send Button Off Screen (iPhone SE)

### ISSUE THREAD

**Issue by oregonisaac** [raedahgroup/dcrios#73]
On the send screen the send button is not visible/selectable.

**Comment by oregonisaac** [comment]
![3b8119b9-07d9-4701-b57b-b924881646ce](https://user-images.githubusercontent.com/4402603/45919271-7f26ba00-be47-11e8-8a7d-56b203953f03.jpeg)

**Comment by oregonisaac** [comment]
This is resolved in most recent release.

**Comment by macsleven** [comment]
Resolved in
https://github.com/raedahgroup/dcrios/pull/91
