### ISSUE TITLE
Overview Shows 0 Balance on Initial Launch

### ISSUE THREAD

**Issue by oregonisaac** [raedahgroup/dcrios#75]
This could be a security feature I suppose, but if not intentional when the wallet is first launched he overview shows 0dcr then after toggling between accounts or waiting a bit it updates.

Probably better for folks stomachs to set it to show “loading” instead of 0 balance while loading.
![ccef71c2-0307-41c9-b0fc-f1957c1516a4](https://user-images.githubusercontent.com/4402603/45919378-3cfe7800-be49-11e8-87bb-cce998716bf6.jpeg)

**Comment by raedah** [comment]
Should be the same as android,  https://github.com/decred/dcrandroid/issues/151

**Comment by macsleven** [comment]
This was fixed ind #98
