### ISSUE TITLE
Send: Numeric keyboard

### ISSUE THREAD

**Issue by hermanlim** [raedahgroup/dcrios#79]
Numeric keyboard does not pop up when the 'blue bar' is tapped all the time. The numeric keyboard only shows up when the left half of the blue bar is pressed. 
[iphoneX, ios 12]

**Comment by macsleven** [comment]
This can’t be replicated...the keyboard pops up every time

**Comment by hermanlim** [comment]
Encountered this bug on a different app. That dev said the problem was due to third party keyboard being used (in this case gBoard).




On 16 February 2019 at 11:29:23, Abubakar Suleiman (notifications@github.com) wrote:

This can’t be replicated...the keyboard pops up every time
