### ISSUE TITLE
Send: QR scanner

### ISSUE THREAD

**Issue by hermanlim** [raedahgroup/dcrios#82]
1. non 'apple standard' icon used to select front facing camera
2. Camera for scanning QR codes closes without explaination when "non Decred"/Generic QR code is scanned
-> would it be practical to display the 'wallet address' of the scanned QR code and ask the user if that was the correct code?

**Comment by oregonisaac** [comment]
Also get an error when scanning a QR code generated in the app itself:

![warning when scanning barcode generated in ios mobile wallet](https://user-images.githubusercontent.com/4402603/46992621-d1ae6b80-d0bf-11e8-86ab-48257ed38db7.jpg)
