### ISSUE TITLE
seedphrase autocomplete with 2 options of same word

### ISSUE THREAD

**Issue by Guang168** [raedahgroup/dcrios#84]
when re-typing my seed phrase, there were 2 options for the word "orca" 

![2018-10-01 09 19 42](https://user-images.githubusercontent.com/43533453/46265670-52675680-c55b-11e8-8678-9e39f255446a.jpg)

**Comment by macsleven** [comment]
Does “orca” appears twice in your seed?

**Comment by Guang168** [comment]
yes. but i thought autocomplete shouldnt have my seed info.
