### ISSUE TITLE
app crashes when try to send funds

### ISSUE THREAD

**Issue by Guang168** [raedahgroup/dcrios#86]
Tried to send funds, 

first crash - when i key in the wrong wallet password and click confirm. 
2nd crash - when i key in the wrong wallet password and reenter the right password and click confirm. 
3rd crash - when i key in right password and click confirm. 

All crashes happen after clicking confirm, hp goes into black screen for half a sec and back to the home screen.

**Comment by macsleven** [comment]
We are Still working on the bug here...

**Comment by oregonisaac** [comment]
FYI I am experiencing same issue.  Any update/change @macsleven ?

**Comment by C-ollins** [comment]
This bug has been fixed at and is currently going through test.

**Comment by macsleven** [comment]
Sending funds  works on the following tested device without crashing:
1. iPhone 5.
2. iPhone SE.
3. iPod Touch.
Which  are devices with less memory and processors.

**Comment by raedah** [comment]
This crash is no longer appearing in recent tests.
