### ISSUE TITLE
Button hidden behind keyboard on "Create Security PassPhrase"

### ISSUE THREAD

**Issue by oregonisaac** [raedahgroup/dcrios#94]
On an iPhoneSE running latest iOS unable to click the button (maybe it says "confirm"?) due to the keyboard covering large portion of the screen.

![image](https://user-images.githubusercontent.com/4402603/46511736-23740d80-c805-11e8-84a1-cca3f934b523.png)

**Comment by macsleven** [comment]
Tapping outside the keyboard doesn’t hide the keyboard?

**Comment by oregonisaac** [comment]
No, no change when tapping outside the keyboard.
